### ISSUE TITLE
[Feature Request] default support for Typescript

### ISSUE THREAD

**Issue by Shougo** [zxqfl/TabNine#28]
This is my configuration.

```toml
[language.typescript]
command = "typescript-language-server"
args = ["--stdio"]
install = [["npm", "install", "-g", "typescript-language-server"]]
```
