### ISSUE TITLE
bingo does not work

### ISSUE THREAD

**Issue by Shougo** [zxqfl/TabNine#41]
I have tested bingo language server instead of go-langserver.
But it does not work with TabNine.
https://github.com/saibing/bingo

@zxqfl Can you test it?

My configuration.

```toml
[language.go]
command = "bingo"
args = ["-mode", "stdio"]
install = [["go", "get", "-u", "github.com/saibing/bingo"]]
```

* It works with vim-lsp
* "go-langserver" works with TabNine
* bingo needs Go 1.11+
