### ISSUE TITLE
ElixirLS runs manually but cannot be started by TabNine

### ISSUE THREAD

**Issue by jc00ke** [zxqfl/TabNine#58]
First, I want to say that even with `no_sem` my jaw consistently drops at how good this tool is. I think you did an amazing job!

I'm trying to get [elixir_ls](https://github.com/JakeBecker/elixir-ls) set up, and I keep getting the following error:
![image](https://user-images.githubusercontent.com/18191/54705844-e8d40800-4afa-11e9-8b81-53cc0775da88.png)
I've manually installed the ls and I can get it to run with the same command in my `TabNine.toml` file:

```toml
[language.elixir]
command = "sh /home/jesse/src/elixir-ls/rel/language_server.sh"
```
![image](https://user-images.githubusercontent.com/18191/54705987-2769c280-4afb-11e9-88ee-2a973dcd3767.png)

Is there something I'm missing?
